project(storage)
add_library(storage STATIC ../start.c ../json.c)
add_executable(start_test ../start_test.c ../ok.c)
target_link_libraries(start_test storage)
add_executable(json_test ../json_test.c ../ok.c)
target_link_libraries(json_test storage)
